kind: ConfigMap 
apiVersion: v1 
metadata:
  name: goshelly-configmap 
data:
  notemail: all@araalinetworks.com
  mode: DEMO
  slacken: "true"
  emailen: "false"
  sslEmail: goshellydemo@araalinetworks.com
  port: "443"
---
apiVersion: v1
kind: Secret
data:
  slackhook:  aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVEM4RlYxVjhSL0IwM003Uko2WEZZLzdQRmZBbkthRk8xaUN6WXJuOHdTVTV5WQ==
metadata:
  name: goshelly-slack-hook
  namespace: default
type: Opaque