kind: ConfigMap 
apiVersion: v1 
metadata:
  name: goshelly-configmap 
data:
  notemail: all@araalinetworks.com
  mode: DEMO
  slacken: "true"
  emailen: "true"
  sslEmail: goshellydemo@araalinetworks.com
  port: "443"
---
apiVersion: v1
kind: Secret
data:
  slackhook:
metadata:
  name: goShelly-slack-hook
  namespace: default
type: Opaque